###Get all users

GET http://localhost:3000/api/users HTTP/1.1

### Get a single user

GET http://localhost:3000/api/users/David HTTP/1.1

### Get a single user who doesn’t exist

GET http://localhost:3000/api/users/Rolf HTTP/1.1

### Delete a user
DELETE http://localhost:3000/api/users/David 